#! /usr/bin/python
# Make sure the PYTHONSTARTUP environment variable is pointing to this file
# something like PYTHONSTARTUP="$HOME/dotfiles/pythonstartup"

import os
import math
import sys
import pygame
from collections import *

def pythagoras(x, y):
    return math.sqrt(x ** 2 + y ** 2)
